language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: RP6VcwTlzFtb5I3AtGikzJoUaVrsBm41SfWohnegxy888FZUhLGFOvb100QMVWZf+iks4Ctn2MJx70ZdGLx+uODCtMPB6MqJVeNfXn+G0aoVLHzogywlEnscB/vwIFp2w1Q0xjHLorNPzWkW19NA3o/pgPICNI5ejAFzHDiZmEvAhKuLLUrjsNbl7ZoLGm9L2Gi8Zy7zsMK0VZZALsgVSps6rLMvhCQ/BASE5jeXplELHiiZFfMYbEQc2vib1+E6l7Dwun9zF2WcLm3WK/qas0F3ztFiIeQatKjjou8YeWyK+T+5V2KL+q6jffXBx8qVNRW8d9WlPeNvJVlZcKQaIU30hpKwUFnTGPWpHUwZb9SfzOh7aECIIIgEFdwlyGkEIsr76cQj8ARrijLpMgKFLIm8b/vcHF3J/zV4j2SQ02oKbVU17urwSQFrImkTCoG0EKuU9i9ZXsf1jcHL6zkoiaHaR38gd2gdXSUYx0pW5GofR95+6y2QxBxOzNv8oPaBXVofoO+IEIorGITr9zNPaHclhUmpZmbl8xxbJGuseE8UlwzfFijS/YBEdOv87TdJ/GAT9SDLOSUaHBi+s4htEbIuG24tgi2z5S3EhoJsqX8s1eYs0V2hjJ0lUKUcxl2b9Ke0Z98Ub326lHPGRvEse5nXLEja7x2Ew6IctV4T0dM=
  app: fast-crag-96970
  on:
    repo: brianlpham21/blog-api
